import React from "react";
import "./sharedCSS.css";
import Numbers from "./components/numbers";
import Head from "next/head";
import Navbar from "./components/navbar";
import Chart from "./components/chart";
import "./sharedCSS.css";
import Minimenu from "./components/minimenu";

export async function getData() {
  const res = await fetch("https://6524d386ea560a22a4ea24ca.mockapi.io/data1");
  return res.json();
}
const Home = async () => {
  const users = await getData();

  return (
    <div className="container">
      <Head>
        <title>Dashboard </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="firstPage">
        <Minimenu />
        <h1>MEDICAL DASHBOARD</h1>
        <Numbers users={users} />
        <Chart />
      </div>
    </div>
  );
};

export default Home;
